import { Mood, BulletinFormat } from "@social-tv/shared";

export const MOODS: Mood[] = [
  {
    id: "focused",
    label: "Focused",
    emoji: "🎯",
    description: "I need signal, not noise",
    boostTags: ["work", "productivity", "tech", "AI", "finance", "business"],
    suppressTags: ["memes", "entertainment", "sports", "funny"],
    preferFormats: ["flash", "top10"],
    accentColor: "#3b82f6",
  },
  {
    id: "curious",
    label: "Curious",
    emoji: "🧠",
    description: "Show me something interesting",
    boostTags: ["science", "space", "research", "deep", "explainer"],
    suppressTags: [],
    preferFormats: ["deep_dive", "top100"],
    accentColor: "#8b5cf6",
  },
  {
    id: "chill",
    label: "Chill",
    emoji: "😌",
    description: "Light browsing, no stress",
    boostTags: ["entertainment", "funny", "lifestyle", "art", "music", "travel"],
    suppressTags: ["politics", "conflict", "finance", "breaking"],
    preferFormats: ["hundred_in_hundred", "top10"],
    accentColor: "#10b981",
  },
  {
    id: "stressed",
    label: "Stressed",
    emoji: "😤",
    description: "Quick catch-up, then done",
    boostTags: ["summary", "tldr", "highlights"],
    suppressTags: ["conflict", "negative", "breaking", "crisis"],
    preferFormats: ["flash"],
    accentColor: "#f59e0b",
  },
  {
    id: "energised",
    label: "Energised",
    emoji: "⚡",
    description: "Bring everything, I'm ready",
    boostTags: [],
    suppressTags: [],
    preferFormats: ["hundred_in_hundred", "top100", "top10"],
    accentColor: "#ef4444",
  },
];

export const BULLETIN_FORMATS: BulletinFormat[] = [
  {
    id: "flash",
    name: "Flash Briefing",
    emoji: "⚡",
    description: "Voiced catch-up — one sentence per story, done in minutes",
    minMinutes: 2,
    maxMinutes: 10,
    storyCount: 5,
    autoAdvance: true,
    voicedByDefault: true,
  },
  {
    id: "top10",
    name: "Top 10",
    emoji: "🔢",
    description: "The 10 most important things across all your channels today",
    minMinutes: 5,
    maxMinutes: 15,
    storyCount: 10,
    autoAdvance: false,
    voicedByDefault: false,
  },
  {
    id: "top100",
    name: "Top 100",
    emoji: "💯",
    description: "Full ranked digest — scroll at your own pace",
    minMinutes: 15,
    maxMinutes: 60,
    storyCount: 100,
    autoAdvance: false,
    voicedByDefault: false,
  },
  {
    id: "hundred_in_hundred",
    name: "100 in 100",
    emoji: "🚀",
    description: "100 headlines in 100 seconds — rapid-fire auto-advancing",
    minMinutes: 2,
    maxMinutes: 2,
    storyCount: 100,
    autoAdvance: true,
    voicedByDefault: false,
  },
  {
    id: "deep_dive",
    name: "Deep Dive",
    emoji: "🔭",
    description: "Pick one topic — every angle from every channel",
    minMinutes: 10,
    maxMinutes: 30,
    storyCount: 20,
    autoAdvance: false,
    voicedByDefault: false,
  },
];

export const TIME_SLOTS = [
  { id: "morning", label: "Morning", emoji: "🌅", defaultTime: "08:00" },
  { id: "lunch",   label: "Lunch",   emoji: "☀️",  defaultTime: "12:30" },
  { id: "evening", label: "Evening", emoji: "🌆", defaultTime: "18:00" },
  { id: "custom",  label: "Custom",  emoji: "⏰",  defaultTime: "09:00" },
];

export const AVAILABLE_MINUTES = [2, 5, 10, 15, 20, 30, 60];
